### ISSUE TITLE
Dynamic routes /{id} needed or dynamic data loading

### ISSUE THREAD

**Issue by fahadmajeed** [pianomansam/serverless-offline-http-mock#27]
It would be good if we can specify /{id} based on specific PUT, DELETE, POST requests with dynamic data

Like in mocks/example.js:
`
'use strict';

const Put = (nock, hostname, **event**) => {
  nock(hostname)
    .persist()
    **.put(`/{id}`, {...event})**
    .reply(200, 'success!');
}
module.exports = Put;`
Or if we can already do this, please point me to right direction.

**Comment by pianomansam** [comment]
Anything that nock supports is supported by this project. Please investigate the nock documentation to see if this is possible
