### ISSUE TITLE
Conditionally run the serverless-offline-http-mock

### ISSUE THREAD

**Issue by amang95** [pianomansam/serverless-offline-http-mock#34]
I am running my serverless service locally using serverless-offline for development purposes. 
I turned to serverless-offline-http-mock to send mock responses when I run functional test environment for the service. However, it also returns mocks when I am not in the test environment.

I was wondering if there is a way to define a condition that when satisfied, would trigger the http-mock to act?

**Comment by pianomansam** [comment]
Resolved in #35
